### ISSUE TITLE
Run without GPU

### ISSUE THREAD

**Issue by JpKuo24** [USC-NSL/Caesar#1]
Can the code run with CPU? For main_mobile.py, I can get the result without GPU. But I stuck on the tracking/act detection part, and when I use _top_ to check the CPU, I don't find any processes. 
Therefore, I just want to know can this code run with CPU and do I need to change any codes to get the final results.

**Comment by hyperchris** [comment]
Hi! All the nodes should be able to run without GPU (although very slow). Did you get any error or get stuck somewhere when running main_tracker.py If so, could you paste the terminal output here? 
One possible reason is that the tracker node doesn't receives data so it just sleeps.

**Comment by JpKuo24** [comment]
Ok, I fix it. The code can work now. Thanks
