### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow-probability-gpu

### ISSUE THREAD

**Issue by huybg-1975** [USC-NSL/Caesar#2]

**Comment by hyperchris** [comment]
Here is my installed pkg list that works:
tensorflow-estimator          1.14.0                
tensorflow-gpu                1.12.0                
tensorflow-probability        0.5.0                 
tensorflow-probability-gpu    0.4.0

You could use ```pip install tensorflow-probability-gpu==0.4.0``` to install it.

Hope it helps!
